#!/usr/bin/env bash
#
# Runs clang-tidy over KArchive's library sources.
#
# Reproduce with:   ./clang_tidy/run_clang_tidy.sh
# Requires:         clang-tidy >= 18, cmake, ninja, python3,
#                   Qt >= 6.8, extra-cmake-modules >= 6.21
#
# Outputs (all committed):
#   clang_tidy/clang_tidy_report.txt   raw findings with source context
#   clang_tidy/summary.txt             finding counts per check and per file
#
# The check selection lives in the repository's .clang-tidy file, so that this
# script and an editor-integrated clang-tidy agree. An earlier version passed
# -checks='-*,bugprone-*' here, which silently overrode .clang-tidy and meant
# the modernize-*, performance-* and readability checks configured there never
# actually ran.
#
# The analysed submodule is never modified. An earlier version applied
# custom.patch and ran `git checkout .` inside vendor/karchive to undo it;
# that would silently discard any local work in there.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT_DIR/build-analysis"
SRC_DIR="$ROOT_DIR/vendor/karchive/src"
OUT_DIR="$ROOT_DIR/clang_tidy"
REPORT="$OUT_DIR/clang_tidy_report.txt"

if [ ! -e "$SRC_DIR/karchive.cpp" ]; then
    echo "error: vendor/karchive is empty. Run: git submodule update --init" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. A build is needed only for compile_commands.json and the generated
#    headers the sources include (karchive_export.h, karchive_version.h).
# ---------------------------------------------------------------------------
echo ">> configuring $BUILD_DIR"
cmake -S "$ROOT_DIR" -B "$BUILD_DIR" -G Ninja \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DBUILD_TESTING=OFF >/dev/null

echo ">> generating headers"
cmake --build "$BUILD_DIR" --target KF6Archive_autogen >/dev/null

# ---------------------------------------------------------------------------
# 2. Analyse. ECMQmLoader is generated by ECM, not written by the KArchive
#    authors, so it is excluded along with the moc output.
# ---------------------------------------------------------------------------
mapfile -t SOURCES < <(ls "$SRC_DIR"/*.cpp | grep -v ECMQmLoader)

# --header-filter is anchored at the absolute source path so that findings in
# generated headers under $BUILD_DIR/vendor/karchive/src/ are excluded; see the
# comment in .clang-tidy. This narrows paths only, never the check selection.
echo ">> running clang-tidy over ${#SOURCES[@]} source files"
clang-tidy "${SOURCES[@]}" \
    -p "$BUILD_DIR" \
    --header-filter="^$SRC_DIR/" \
    --extra-arg='-w' \
    > "$REPORT" 2>&1 || true

# Paths are absolute and machine-specific; make them repository-relative so the
# committed report is stable across machines.
sed -i "s|$ROOT_DIR/||g" "$REPORT"

# ---------------------------------------------------------------------------
# 3. Summarise.
# ---------------------------------------------------------------------------
echo ">> summarising"
python3 - "$REPORT" "$OUT_DIR/summary.txt" <<'PY'
import sys, re, collections
report, out = sys.argv[1], sys.argv[2]

# A finding line looks like:  path:line:col: warning: message [check-name]
line_re = re.compile(r"^(?P<file>[^:\n]+):\d+:\d+: (?P<sev>warning|error): .*\[(?P<checks>[a-z0-9,\-]+)\]$")

by_check, by_file, by_sev = collections.Counter(), collections.Counter(), collections.Counter()
total = 0
for line in open(report, errors="replace"):
    m = line_re.match(line.rstrip("\n"))
    if not m:
        continue
    total += 1
    by_sev[m.group("sev")] += 1
    by_file[m.group("file")] += 1
    # One finding can be attributed to several aliased checks.
    for check in m.group("checks").split(","):
        by_check[check] += 1

with open(out, "w") as f:
    f.write(f"clang-tidy findings: {total}\n\n")
    f.write("By severity\n")
    for sev, n in by_sev.most_common():
        f.write(f"  {n:5d}  {sev}\n")
    f.write("\nBy check\n")
    for check, n in by_check.most_common():
        f.write(f"  {n:5d}  {check}\n")
    f.write("\nBy file\n")
    for fn, n in by_file.most_common():
        f.write(f"  {n:5d}  {fn}\n")
print(open(out).read())
PY

echo ">> report written to ${REPORT#"$ROOT_DIR"/} ($(wc -l < "$REPORT") lines)"
